/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Options passed to [`PdfBro::create`]. */
export interface CreateOptions {
  /** Which engines to enable. Defaults to `["chromium", "office"]`. */
  engines?: Array<string>
  /** Explicit path to a Chrome/Chromium executable. */
  chromePath?: string
  /** Automatically download Chrome if no system Chrome is found. */
  autoDownloadChrome?: boolean
  /** Directory used to cache downloaded Chrome binaries. */
  chromeCacheDir?: string
}
/** Async PdfBro client that wraps the PDF/document engines. */
export declare class PdfBro {
  /** Create a new PdfBro instance, launching the requested engines. */
  static create(opts?: CreateOptions | undefined | null): Promise<PdfBro>
  /** Convert an HTML string to a PDF buffer. */
  htmlToPdf(html: string, options?: Json | undefined | null): Promise<Buffer>
  /** Convert a URL to a PDF buffer. */
  urlToPdf(url: string, options?: Json | undefined | null): Promise<Buffer>
  /** Convert a Markdown string to a PDF buffer. */
  markdownToPdf(md: string, options?: Json | undefined | null): Promise<Buffer>
  /** Convert an office document at `path` to a PDF buffer. */
  officeToPdf(path: string, options?: Json | undefined | null): Promise<Buffer>
  /** Shut down the PdfBro instance and release resources. */
  close(): Promise<void>
}
